 version: '3.8'
 services:
   api-student-33:
     build: .
     ports:
       - "3033:3000"
     environment:
       DB_URL: mongodb://mongo-student-33:27017/CRMdb-student-33
       PORT: 3000
     depends_on:
       - mongo-student-33
   mongo-student-33:
     image: mongo:latest
     ports:
       - "27050:27017"
     volumes:
       - db-data-student-33:/data/db
 volumes:
   db-data-student-33: